india_market_scheduled_task_sleeping = 900
generic_market_scheduled_task_sleeping = 800
news_sentiment_calculation_task_sleeping = 1000


twitter_sentiment_calculation_task_sleeping = 2000
twitter_data_scheduled_task_sleeping = 1000

indices_scheduled_task_sleeping = 5000
